swagger: "2.0"
info:
  description: "This is a sample server celler server."
  title: "Swagger Example API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "API Support"
    url: "http://www.swagger.io/support"
    email: "support@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0"
host: "localhost:9090"
basePath: "/api/v1"
paths:
  /ping:
    get:
      description: "do ping"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "example"
      summary: "ping example"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
  /odontologos:
    post:
      description: "Crea un nuevo odontologo"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "odontologo"
      summary: "odontologo ejemplo"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
  /odontologos/{id}:
    get:
      description: "Trae a un odontologo por su id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "odontologo"
      summary: "odontologo ejemplo"
      parameters:
        - type: "integer"
          description: "id del odontologo"
          name: "id"
          in: "path"
          required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    put:
      description: "Actualiza al odontologo completo"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "odontologo"
      summary: "odontologo ejemplo"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    patch:
      description: "Actualiza parcialmente al odontologo"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "odontologo"
      summary: "odontologo ejemplo"
      parameters:
        - type: "integer"
          description: "id del odontologo"
          name: "id"
          in: "path"
          required: true
        - type: "object"
          description: "Campos a actualizar"
          name: "updateData"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/dentistUpdateData"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    delete:
      description: "Borrar odontologo por id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "odontologo"
      summary: "odontologo ejemplo"
      parameters:
        - type: "integer"
          description: "id del odontologo"
          name: "id"
          in: "path"
          required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
  /pacientes:
    post:
      description: "Crea un nuevo paciente"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "paciente"
      summary: "paciente ejemplo"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
  /pacientes/{id}:
    get:
      description: "Trae a un paciente por su id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "paciente"
      summary: "paciente ejemplo"
      parameters:
        - type: "integer"
          description: "id del paciente"
          name: "id"
          in: "path"
          required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    put:
      description: "Actualiza al paciente por id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "paciente"
      summary: "paciente ejemplo"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    patch:
      description: "Actualiza parcialmente al paciente"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "paciente"
      summary: "paciente ejemplo"
      parameters:
        - type: "integer"
          description: "ID del paciente"
          name: "id"
          in: "path"
          required: true
        - type: "object"
          description: "Campos a actualizar"
          name: "updateData"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/dentistUpdateData"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    delete:
      description: "Borrar paciente por id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "paciente"
      summary: "paciente ejemplo"
      parameters:
        - type: "integer"
          description: "id del paciente"
          name: "id"
          in: "path"
          required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
  /turnos:
    post:
      description: "Crea un nuevo turno"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "turno"
      summary: "turno ejemplo"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
  /turnos/{id}:
    get:
      description: "Get turnos by id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "turno"
      summary: "turno ejemplo"
      parameters:
        - type: "integer"
          description: "id del turno"
          name: "id"
          in: "path"
          required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    put:
      description: "Actualiza al turno por id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "turno"
      summary: "turno ejemplo"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    patch:
      description: "Actualiza parcialmente al turno"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "turno"
      summary: "turno ejemplo"
      parameters:
        - type: "integer"
          description: "id del turno"
          name: "id"
          in: "path"
          required: true
        - type: "object"
          description: "Campos a actualizar"
          name: "updateData"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/dentistUpdateData"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
    delete:
      description: "Borrar turno por id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "turno"
      summary: "turno ejemplo"
      parameters:
        - type: "integer"
          description: "id del paciente"
          name: "id"
          in: "path"
          required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
  /turnos/dni/{dni}:
    post:
      description: "Crea un nuevo turno para un paciente"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "turno"
      summary: "turno ejemplo"
      parameters:
        - type: "string"
          description: "DNI del paciente"
          name: "dni"
          in: "path"
          required: true
        - type: "object"
          description: "Campos del turno"
          name: "appointmentData"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/appointmentData"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/web.response"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
  /turnos/dni/{dni}:
    get:
      description: "Busca un turno por el dni del paciente"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      tags:
        - "turno"
      summary: "turno ejemplo"
      parameters:
        - type: "string"
          description: "DNI del paciente"
          name: "dni"
          in: "path"
          required: true
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/appointmentData"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/web.errorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/web.errorResponse"
definitions:
  web.errorResponse:
    type: "object"
    properties:
      code:
        type: "string"
      message:
        type: "string"
  web.response:
    type: "object"
    properties:
      data: {}
  dentistUpdateData:
    type: "object"
    properties:
      nombre:
        type: "string"
      apellido:
        type: "string"
      matricula:
        type: "string"
  appointmentData:
    type: "object"
    properties:
      paciente:
        type: "string"
      odontologo:
        type: "string"
      fecha_hora:
        type: "integer"
      descripcion:
        type: "integer"
securityDefinitions:
  BasicAuth:
    type: "basic"